[project]
name = 'naboo'
version = '0.1.26'
description = ''

license = 'MIT'

authors = [{name = 'Brendan Doms'}]

readme = 'README.md'

requires-python = '>=3.12'

dependencies = [
    'asyncpg == 0.31.0'
]

[project.urls]
repository = 'https://github.com/bdoms/naboo'
homepage = 'https://github.com/bdoms/naboo'

[dependency-groups]
dev = [
    'pytest == 9.1.1',
    'pytest-asyncio == 1.4.0',
    'pytest-env == 1.7.1',
    'ruff == 0.16.7'
]
